# The testing matrix considers ruby/puppet versions supported by SIMP and PE:
#
# https://puppet.com/docs/pe/2018.1/component_versions_in_recent_pe_releases.html
# https://puppet.com/misc/puppet-enterprise-lifecycle
# https://puppet.com/docs/pe/2018.1/overview/getting_support_for_pe.html
# ------------------------------------------------------------------------------
# Release       Puppet   Ruby   EOL
# PE 2016.4.15  4.10.12  2.1.9  2018-12 (LTS)
# SIMP 6.0      4.8.2    2.1.9  TBD
# SIMP 6.1      4.10.6   2.1.9  TBD
# SIMP 6.2      4.10.12  2.1.9  TBD
# SIMP 6.3      5.5.7    2.4.4  TBD***
# PE 2018.1     5.5.6    2.4.4  2020-05 (LTS)***
#
# *** = Modules created for SIMP 6.3+ are not required to support Puppet < 5.5
---
language: ruby
cache: bundler
sudo: false

bundler_args: --without development system_tests --path .vendor

notifications:
  email: false

addons:
  apt:
    packages:
      - rpm

before_install:
  - rm -f Gemfile.lock
  - gem update --system

jobs:
  include:
    - stage: check
      rvm: 2.4.4
      env: STRICT_VARIABLES=yes PUPPET_VERSION="~> 5.5"
      script:
        - bundle exec rake check:dot_underscore
        - bundle exec rake check:test_file
        - bundle exec rake lint
        - bundle exec rake metadata_lint
        - bundle exec rake pkg:check_version
        - bundle exec rake pkg:compare_latest_tag
        - bundle exec rake pkg:create_tag_changelog
        - bundle exec puppet module build

    - stage: spec
      rvm: 2.4.4
      env: STRICT_VARIABLES=yes PUPPET_VERSION="~> 5.5.6"
      script:
        - bundle exec rake spec

    - stage: spec
      rvm: 2.4.4
      env: STRICT_VARIABLES=yes PUPPET_VERSION="~> 5.5"
      script:
        - bundle exec rake spec

    - stage: spec
      rvm: 2.1.9
      env: STRICT_VARIABLES=yes PUPPET_VERSION="~> 4.10.4"
      script:
        - bundle exec rake spec

    # Uncomment the following for deployment tasks and set 'secure' in both
    # sections appropriately
#   - stage: deploy
#     rvm: 2.4.4
#     if: 'fork = false AND tag = true'
#     script:
#       - true
#     before_deploy:
#       - "export PUPMOD_METADATA_VERSION=`ruby -r json -e \"puts JSON.parse(File.read('metadata.json')).fetch('version')\"`"
#       - '[[ $TRAVIS_TAG =~ ^simp-${PUPMOD_METADATA_VERSION}$|^${PUPMOD_METADATA_VERSION}$ ]]'
#     deploy:
#       - provider: releases
#         api_key:
#           secure: ""
#         skip_cleanup: true
#         on:
#           tags: true
#           condition: '($SKIP_FORGE_PUBLISH != true)'
#       - provider: puppetforge
#         user: simp
#         password:
#           secure: ""
#         on:
#           tags: true
#           rvm: 2.4.4
#           condition: '($SKIP_FORGE_PUBLISH != true)'
